#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_PATH=$( cd "$DIR/.." && pwd )
$DIR/build

echo "Getting available devices"
adb devices

echo "Installing to devices"
adb -s 015d4b340c581814 install -r bin/AshDemo-debug.apk

echo "Starting app..."
adb shell am start -a android.intent.action.MAIN -n pl.ug.ash/pl.ug.ash.AshDemo

